// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// jaccard_coeff
NumericMatrix jaccard_coeff(SEXP R_idx, SEXP R_weight);
RcppExport SEXP _monocle_jaccard_coeff(SEXP R_idxSEXP, SEXP R_weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type R_idx(R_idxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_weight(R_weightSEXP);
    rcpp_result_gen = Rcpp::wrap(jaccard_coeff(R_idx, R_weight));
    return rcpp_result_gen;
END_RCPP
}
// find_closest_point_cpp
Rcpp::IntegerVector find_closest_point_cpp(const Eigen::MatrixXd& Z, const Eigen::MatrixXd& Y, int num_threads);
RcppExport SEXP _monocle_find_closest_point_cpp(SEXP ZSEXP, SEXP YSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(find_closest_point_cpp(Z, Y, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// ddrtree_project_cells_to_mst_cpp
List ddrtree_project_cells_to_mst_cpp(const NumericMatrix& z, const NumericMatrix& y, const IntegerMatrix& graph_edges, const IntegerVector& closest_vertex);
RcppExport SEXP _monocle_ddrtree_project_cells_to_mst_cpp(SEXP zSEXP, SEXP ySEXP, SEXP graph_edgesSEXP, SEXP closest_vertexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type graph_edges(graph_edgesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type closest_vertex(closest_vertexSEXP);
    rcpp_result_gen = Rcpp::wrap(ddrtree_project_cells_to_mst_cpp(z, y, graph_edges, closest_vertex));
    return rcpp_result_gen;
END_RCPP
}
// ddrtree_order_from_edges_cpp
List ddrtree_order_from_edges_cpp(int n_vertices, const IntegerMatrix& edges, const NumericVector& weights, int root_cell);
RcppExport SEXP _monocle_ddrtree_order_from_edges_cpp(SEXP n_verticesSEXP, SEXP edgesSEXP, SEXP weightsSEXP, SEXP root_cellSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_vertices(n_verticesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type root_cell(root_cellSEXP);
    rcpp_result_gen = Rcpp::wrap(ddrtree_order_from_edges_cpp(n_vertices, edges, weights, root_cell));
    return rcpp_result_gen;
END_RCPP
}
// ddrtree_select_root_by_state_cpp
int ddrtree_select_root_by_state_cpp(const NumericMatrix& coords, const IntegerVector& candidate_cells, const NumericVector& pseudotime, const IntegerVector& closest_vertex, bool use_min_pseudotime);
RcppExport SEXP _monocle_ddrtree_select_root_by_state_cpp(SEXP coordsSEXP, SEXP candidate_cellsSEXP, SEXP pseudotimeSEXP, SEXP closest_vertexSEXP, SEXP use_min_pseudotimeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type candidate_cells(candidate_cellsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pseudotime(pseudotimeSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type closest_vertex(closest_vertexSEXP);
    Rcpp::traits::input_parameter< bool >::type use_min_pseudotime(use_min_pseudotimeSEXP);
    rcpp_result_gen = Rcpp::wrap(ddrtree_select_root_by_state_cpp(coords, candidate_cells, pseudotime, closest_vertex, use_min_pseudotime));
    return rcpp_result_gen;
END_RCPP
}
// fast_diff_test_sparse_cpp
Rcpp::List fast_diff_test_sparse_cpp(const Eigen::SparseMatrix<double>& exprs_t, const Eigen::MatrixXd& X_full, const Eigen::MatrixXd& X_red, const Rcpp::NumericVector& disp_guesses, const Rcpp::NumericVector& size_factors, bool relative_expr, int num_threads, std::string family_name);
RcppExport SEXP _monocle_fast_diff_test_sparse_cpp(SEXP exprs_tSEXP, SEXP X_fullSEXP, SEXP X_redSEXP, SEXP disp_guessesSEXP, SEXP size_factorsSEXP, SEXP relative_exprSEXP, SEXP num_threadsSEXP, SEXP family_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type exprs_t(exprs_tSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_full(X_fullSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_red(X_redSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type disp_guesses(disp_guessesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type size_factors(size_factorsSEXP);
    Rcpp::traits::input_parameter< bool >::type relative_expr(relative_exprSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< std::string >::type family_name(family_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_diff_test_sparse_cpp(exprs_t, X_full, X_red, disp_guesses, size_factors, relative_expr, num_threads, family_name));
    return rcpp_result_gen;
END_RCPP
}
// fast_diff_test_dense_cpp
Rcpp::List fast_diff_test_dense_cpp(const Eigen::MatrixXd& exprs, const Eigen::MatrixXd& X_full, const Eigen::MatrixXd& X_red, const Rcpp::NumericVector& disp_guesses, const Rcpp::NumericVector& size_factors, bool relative_expr, int num_threads, std::string family_name);
RcppExport SEXP _monocle_fast_diff_test_dense_cpp(SEXP exprsSEXP, SEXP X_fullSEXP, SEXP X_redSEXP, SEXP disp_guessesSEXP, SEXP size_factorsSEXP, SEXP relative_exprSEXP, SEXP num_threadsSEXP, SEXP family_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type exprs(exprsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_full(X_fullSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_red(X_redSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type disp_guesses(disp_guessesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type size_factors(size_factorsSEXP);
    Rcpp::traits::input_parameter< bool >::type relative_expr(relative_exprSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< std::string >::type family_name(family_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_diff_test_dense_cpp(exprs, X_full, X_red, disp_guesses, size_factors, relative_expr, num_threads, family_name));
    return rcpp_result_gen;
END_RCPP
}
// fast_nb_fit_predict_sparse_cpp
Rcpp::List fast_nb_fit_predict_sparse_cpp(const Eigen::SparseMatrix<double>& exprs_t, const Eigen::MatrixXd& X_fit, const Eigen::MatrixXd& X_pred, const Rcpp::NumericVector& disp_guesses, const Rcpp::NumericVector& size_factors, bool relative_expr, bool want_resid, int num_threads);
RcppExport SEXP _monocle_fast_nb_fit_predict_sparse_cpp(SEXP exprs_tSEXP, SEXP X_fitSEXP, SEXP X_predSEXP, SEXP disp_guessesSEXP, SEXP size_factorsSEXP, SEXP relative_exprSEXP, SEXP want_residSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type exprs_t(exprs_tSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_fit(X_fitSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_pred(X_predSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type disp_guesses(disp_guessesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type size_factors(size_factorsSEXP);
    Rcpp::traits::input_parameter< bool >::type relative_expr(relative_exprSEXP);
    Rcpp::traits::input_parameter< bool >::type want_resid(want_residSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_nb_fit_predict_sparse_cpp(exprs_t, X_fit, X_pred, disp_guesses, size_factors, relative_expr, want_resid, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// fast_nb_fit_predict_dense_cpp
Rcpp::List fast_nb_fit_predict_dense_cpp(const Eigen::MatrixXd& exprs, const Eigen::MatrixXd& X_fit, const Eigen::MatrixXd& X_pred, const Rcpp::NumericVector& disp_guesses, const Rcpp::NumericVector& size_factors, bool relative_expr, bool want_resid, int num_threads);
RcppExport SEXP _monocle_fast_nb_fit_predict_dense_cpp(SEXP exprsSEXP, SEXP X_fitSEXP, SEXP X_predSEXP, SEXP disp_guessesSEXP, SEXP size_factorsSEXP, SEXP relative_exprSEXP, SEXP want_residSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type exprs(exprsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_fit(X_fitSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_pred(X_predSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type disp_guesses(disp_guessesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type size_factors(size_factorsSEXP);
    Rcpp::traits::input_parameter< bool >::type relative_expr(relative_exprSEXP);
    Rcpp::traits::input_parameter< bool >::type want_resid(want_residSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_nb_fit_predict_dense_cpp(exprs, X_fit, X_pred, disp_guesses, size_factors, relative_expr, want_resid, num_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_monocle_jaccard_coeff", (DL_FUNC) &_monocle_jaccard_coeff, 2},
    {"_monocle_find_closest_point_cpp", (DL_FUNC) &_monocle_find_closest_point_cpp, 3},
    {"_monocle_ddrtree_project_cells_to_mst_cpp", (DL_FUNC) &_monocle_ddrtree_project_cells_to_mst_cpp, 4},
    {"_monocle_ddrtree_order_from_edges_cpp", (DL_FUNC) &_monocle_ddrtree_order_from_edges_cpp, 4},
    {"_monocle_ddrtree_select_root_by_state_cpp", (DL_FUNC) &_monocle_ddrtree_select_root_by_state_cpp, 5},
    {"_monocle_fast_diff_test_sparse_cpp", (DL_FUNC) &_monocle_fast_diff_test_sparse_cpp, 8},
    {"_monocle_fast_diff_test_dense_cpp", (DL_FUNC) &_monocle_fast_diff_test_dense_cpp, 8},
    {"_monocle_fast_nb_fit_predict_sparse_cpp", (DL_FUNC) &_monocle_fast_nb_fit_predict_sparse_cpp, 8},
    {"_monocle_fast_nb_fit_predict_dense_cpp", (DL_FUNC) &_monocle_fast_nb_fit_predict_dense_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_monocle(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
